In [ ]:
STRING METHODS
*Upper():Converts the string to uppercase
lowercase():Converts the string to lowercase
strip():removes leading and trailing whitespace

In [19]:
#accessing characters
#string are indexed, starting from (0)
name="khadeeja"
first_letter=[2]#this will be 'a'
last_letter=[-1]#negative indexing start form the end 
print(first_letter)
print(last_letter)

[2]
[-1]


In [33]:
#string slicing
# Message to slice
message = "Hello, world!"

# Get the first word (everything before the space)
first_word = message[: message.find(" ")]  

# Get the last word (everything after the last space)
last_word = message[message.rfind(" ") + 1:]  

# Print the results
print(f"First word: {first_word}")
print(f"Last word: {last_word}")

First word: Hello,
Last word: world!


In [34]:
#string concatination 
first_name="khadeeja"
last_name="Ramzan"
full_name=first_name+""+ last_name
print(full_name)

khadeejaRamzan


In [35]:
#string formatting
name="Bob"
age=30
greeting=f"hello, {name} ! you are {age} years old" 
print(greeting)

hello, Bob ! you are 30 years old


In [36]:
#WORKING WITH INTEGERS 
value1=23
value2=100
average= value1+value2 /2
print("the average is:",average)

the average is: 73.0


In [21]:
#WORKING WITH BOOLEANS
booleant= True
booleanf= False
print(booleant)
print(booleanf)

True
False


In [22]:
#WORKING WITH FLOATS
area=278.9
area2=23.56
total_area=278.9*23.56
print(total_area)

6570.883999999999


In [40]:
#WORKING WITH TUPLES
# Simple tuple with strings
fruits = ("apple", "banana", "cherry")

# Tuple with mixed data types
data = (10, 3.14, True, ["apple", "pie"])  # List inside a tuple

# Tuple with one element (needs a trailing comma)
name = ("Alice",)  # Without the comma, it would become a string
print(fruits)

('apple', 'banana', 'cherry')


In [38]:
#working with dictionaries
dictionary = {'name':'khadija','age': 20}
print(dictionary)

{'name': 'khadija', 'age': 20}


In [25]:
#for looping
fruits=["apple","banana","cherry"]
for fruit in fruits:
    print(fruit)

apple
banana
cherry


In [26]:
#while looping
# Initialize a counter variable
counter = 1
while counter <= 5:
  print(f"Counting: {counter}")
  counter += 1 
print("Finished counting!")

Counting: 1
Counting: 2
Counting: 3
Counting: 4
Counting: 5
Finished counting!


In [27]:
#conditional statement
is_sunny = True  
if is_sunny:
    print("Go outside and enjoy the sunshine!")
else:
    print("Stay cozy inside with a good book!")

Go outside and enjoy the sunshine!


In [28]:
# Create a class called "Car"
class Car:
  def __init__(self, color, model):  
    self.color = color
    self.model = model

  # Define a method (behavior) to describe the car
  def describe(self):
    print(f"This car is a {self.color} {self.model}.")

# Create an object (instance) of the Car class
my_car = Car("red", "Honda Civic")

# Call the method of the object to describe it
my_car.describe()

This car is a red Honda Civic.


In [29]:
# Importing NumPy library
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Printing the array
print("Original Array:", arr)

# Performing some operations on the array
print("Sum of Array Elements:", np.sum(arr))
print("Mean of Array Elements:", np.mean(arr))
print("Standard Deviation of Array Elements:", np.std(arr))

Original Array: [1 2 3 4 5]
Sum of Array Elements: 15
Mean of Array Elements: 3.0
Standard Deviation of Array Elements: 1.4142135623730951


In [30]:

import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Array shape (dimensions)
print(arr.shape)  # Output: (5,) (one-dimensional array)

# Accessing elements
first_element = arr[0]
print(first_element)  # Output: 1

# Slicing (extracting sub-arrays)
sub_arr = arr[1:4]  # From index 1 (inclusive) to 4 (exclusive)
print(sub_arr)  # Output: [2 3 4]

# Array creation with specific data types
float_arr = np.array([1.5, 2.3, 4.2], dtype=float)
print(float_arr.dtype)  # Output: float64

# Mathematical operations (element-wise)
doubled_arr = arr * 2
print(doubled_arr)  # Output: [2 4 6 8 10]

# Other array creation methods
zeros_arr = np.zeros(5)  # Create an array of 5 zeros
ones_arr = np.ones((2, 3))  # Create a 2x3 array of ones
random_arr = np.random.rand(4)  # Create a random array of size 4 (between 0 and 1)

# Array concatenation
combined_arr = np.concatenate((arr, zeros_arr))
print(combined_arr) 

[1 2 3 4 5]
(5,)
1
[2 3 4]
float64
[ 2  4  6  8 10]
[1. 2. 3. 4. 5. 0. 0. 0. 0. 0.]


In [31]:
import pandas as pd
# Creating a DataFrame:
data = {'Name': ['Babar Azam', 'Shahdab', 'Shaheen Shah'],
        'Age': [30, 30, 25],
        "city": ['lahore','lahore','peshawar']}
df = pd.DataFrame(data)
print(df)
df.to_csv("CricketersInfo.csv")

           Name  Age      city
0    Babar Azam   30    lahore
1       Shahdab   30    lahore
2  Shaheen Shah   25  peshawar


In [ ]:
import pandas as pd

df=pd.read_csv("phishing.csv",sep=",")
print(

In [ ]:
# Reading Data from CSV File:
import pandas as pd
df = pd.read_csv('')


In [ ]:
import pandas as pd
df= pd.read_csv('phishing.csv')

In [51]:
df.head()

Name  Age      city
0    Babar Azam   30    lahore
1       Shahdab   30    lahore
2  Shaheen Shah   25  peshawar

In [ ]:
import pandas as pd
df=pd.read_csv('CloudWatch_Web_Attack.csv')
df.head()

In [ ]:
# Basic DataFrame Operations:
print(df.shape)
print(df.columns)
print(df.describe())
print(df['job_title'])

In [ ]:
Country Code Mapping
# Reading Data from CSV File:
df1 = pd.read_csv('Country-Code-Mapping.csv')
print(df1.head())